### ISSUE TITLE
Теряется человек, о котором написан отчёт

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/ITLab-Reports#25]
Если я всё правильно понял, то `reporter` — тот, кто пишет отчёт, а `implementer` — тот, о ком отчёт пишется.

И тут появляется проблема, что, кого бы я ни указал в поле `implementer`, оно меняется на id отправителя.

**Пример**
Тело запроса:
```json
{
  "name":"345678",
  "text":"90-",
  "date":"2021-02-06T08:56:00.998Z",
  "assignees":{
    "reporter":"eb3c6de8-4f7a-4cff-9af3-cd514484b492",
    "implementer":"22ccede6-b4cd-4ac3-923a-7476b2da0812"
  },
  "archived":false
}
```

Ответ:
```json
{
  "id":"601e59a10e7aa03e3f217ac4",
  "assignees":{
    "reporter":"eb3c6de8-4f7a-4cff-9af3-cd514484b492",
    "implementer":"eb3c6de8-4f7a-4cff-9af3-cd514484b492"
  },
  "date":"2021-02-06T08:56:01",
  "text":"90-",
  "archived":false
}
```

**Comment by CAPCHIK** [comment]
Пробовал провернуть такое на сайте? В текущей версии такое же поведение?

**Comment by IvLaptev** [comment]
Да.

Я отправил вот это в разных вариациях:
```json
{
  "name":"345678",
  "text":"Максим, если ты это видишь, то всё ок.",
  "date":"2021-02-06T08:56:00.998Z",
  "assignees":{
    "reporter":"d0b723bb-2fc1-48e5-82a7-7bc2c1d3967b",
    "implementer":"000a4842-0b9f-4656-07d0-08d6081035e4"
  },
  "archived":false
}
```

Всё прилетело в меня

![image](https://user-images.githubusercontent.com/23360152/107117661-e3b60880-688c-11eb-9c2b-c12220fc3abe.png)

![image](https://user-images.githubusercontent.com/23360152/107117666-eb75ad00-688c-11eb-9936-426aeb5c50e2.png)

**Comment by komarb** [comment]
implementer указывается как query параметр в строке запроса 
если его не указать, то автоматически в это поле запишется id того, кто писал report
извиняюсь за #22
